Adding extra options to dev scripts (#380)

diff --git a/dev-scripts/run-e2e-tests b/dev-scripts/run-e2e-tests
--- a/dev-scripts/run-e2e-tests
+++ b/dev-scripts/run-e2e-tests
@@ -1,6 +1,16 @@
 #!/bin/bash
 
-set -xe
+# Exit build script on first failure
+set -e
+
+# Echo commands to stdout.
+set -x
+
+if [ "$1" = "--skip-build" ]; then
+  flags=""
+else
+  flags="--build"
+fi
 
 cd e2e
 docker-compose up --exit-code-from cypress --abort-on-container-exit --build
